Check goimports

diff --git a/.github/workflows/go-test.yml b/.github/workflows/go-test.yml
--- a/.github/workflows/go-test.yml
+++ b/.github/workflows/go-test.yml
@@ -35,5 +35,14 @@ jobs:
         run: go vet ./...
       - name: Static checks with Staticcheck
         run: go run honnef.co/go/tools/cmd/staticcheck ./...
+      - name: Check imports
+        run: go run golang.org/x/tools/cmd/goimports -w .
       - name: Test with the Go CLI.
         run: go test -v ./...
+      - name: Verify repo is up-to-date
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo 'Updates required:'
+            git status
+            exit 1
+          fi
